### ISSUE TITLE
Rename the first 9 numbers as 01, 02, 03...

### ISSUE THREAD

**Issue by fedegitter** [Leone25/pdf-to-image#1]
Ciao!
Lo strumento è fantastico, come tutti gli altri che hai creato. Ti faccio i complimenti e ti ringrazio!

Vorrei chiederti se fosse possibile aggiungere la possibilità di rinominare automaticamente i file 1, 2, 3, 4, 5, 6, 7, 8, 9 con lo zero davanti... in modo che nella cartella abbiano un ordine, altrimenti dopo il file 1 viene subito il 10... Io uso il tuo strumento per copiare tutte le immagini in file Word, e devo quindi rinominare tutti i file fino al 9 con lo zero davanti in modo che seguano un ordine sequenziale. 

Il problema si pone anche per le pagine dopo il 100, però in questo caso non saprei come si potrebbe risolvere... dovrebbe ripartire con 99_1, 99_2 etc.? Questo comunque è un problema minore, perchè le slide a lezione raramente superano le 100 :-D

PS. 
Posso chiederti la funzione "scale" a cosa serve? A ridimensionare le immagini? Se sì, in che termini vengono ridimensionate...?

Grazie ancora!

Saluti

**Comment by Leone25** [comment]
ciao, certo si può fare, per la questione delle pagine oltre alla cento io posso proporre che in caso ce ne siano più di cento si aggiungano 2 zeri prima dei numeri per le cifre singole e 1 per le cifre doppie.

"scale" è un valore misterioso anche per me devo ammettere, però credo che la libreria che fa effettivamente la conversione prenda la dimensione della pagina del pdf (che tecnicamente non ha unita), moltiplica per il valore scala e quella diventa la risoluzione in pixel

**Comment by Leone25** [comment]
ps. ho già implementato la nuova funzione, ricordati di svuotare le cache, se non lo sai fare usa semplicemente una pagina in incognito

**Comment by fedegitter** [comment]
Ottimo, adesso per me è perfetto!!! 
Sì, scale ho visto che il valore più è vicino a 0 più è compresso...
Ti ringrazio ancora!
